mightyiam/files migration issue
In this commit:
https://github.com/mightyiam/files/commit/45dc3cbd093b1e55caf37324c425203903b88434
the suggestion is to use `inputs.files + "/flake-module.nix"` instead of
`inputs.files + "/module.nix"`. While this resolves the missing file
error, I now get this instead:
```bash
infra on  mightyiam_files_migration [$]
❯ nix flake check -L
error:
       … while checking flake output 'checks'

       … while evaluating the attribute 'optionalValue.value'
         at «https://releases.nixos.org/nixpkgs/nixpkgs-26.05pre998534.d233902339c0/nixexprs.tar.xz?narHash=sha256-vZOcDniDPc1cS8A4Xi5YE6AGyPIvEpy4GMyayA3SWIM%3D»/lib/modules.nix:1330:5:
         1329|
         1330|     optionalValue = if isDefined then { value = mergedValue; } else { };
             |     ^
         1331|   };

       … while evaluating a branch condition
         at «https://releases.nixos.org/nixpkgs/nixpkgs-26.05pre998534.d233902339c0/nixexprs.tar.xz?narHash=sha256-vZOcDniDPc1cS8A4Xi5YE6AGyPIvEpy4GMyayA3SWIM%3D»/lib/modules.nix:1330:21:
         1329|
         1330|     optionalValue = if isDefined then { value = mergedValue; } else { };
             |                     ^
         1331|   };

       … while evaluating definitions from `/nix/store/ch5n4xdddid5859dy6c4i6lghqyx8016-source/modules/transposition.nix':

       … while evaluating the option `perSystem.x86_64-linux.checks':

       … while evaluating definitions from `/nix/store/445f8641h2wi2zjxb7zjikcgb2bc8fws-source/flake-module.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `perSystem.x86_64-linux.files.files."[definition 1-entry 1]".path_' does not exist. Definition values:
       - In `/nix/store/lwk2zgcb5ajkskfx6k0ijdapgvarfbw7-source/modules/git/ignore.nix, via option perSystem': ".gitignore"

       Did you mean `perSystem.x86_64-linux.files.files."[definition 1-entry 1]".path' or `perSystem.x86_64-linux.files.files."[definition 1-entry 1]".drv'?
```